# Generated by Django 6.0.1 on 2026-02-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roommembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
    ]
