# Generated by Django 6.0.1 on 2026-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='background_preset',
            field=models.CharField(default='img1', max_length=50),
        ),
    ]
