# Generated by Django 6.0.1 on 2026-02-21 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair', models.CharField(default='Default Hair', max_length=50)),
                ('face_expression', models.CharField(default='Neutral', max_length=50)),
                ('clothes', models.CharField(default='Default Clothes', max_length=50)),
                ('skin_color', models.CharField(default='Medium', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
