# Generated by Django 6.0.1 on 2026-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='focus_goal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(default='', max_length=500),
        ),
    ]
