# Generated by Django 6.0.1 on 2026-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_focus_goal_userprofile_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(default='profile_pic.png', max_length=100),
        ),
    ]
