# Generated by Django 6.0.1 on 2026-04-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roomlinkmessage_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
